### ISSUE TITLE
`isObserved` and `getThreadCount` deprecated?

### ISSUE THREAD

**Issue by ben-pr-p** [NathanaelA/v8-Natives#10]
Hello -

Were those two methods deprecated in a later version of Node (> 7)? I got undefined errors when requiring `v8-natives`, and the problem was fixed by commenting those definitions out in the source.

**Comment by NathanaelA** [comment]
It is possible; >7 is using a much later v8 engine and the v8 team has revamped some stuff in the v8 50.x branches...    I'll check the current exported list...

**Comment by ben-pr-p** [comment]
Where do you find the current exported list? I'm currently developing an Atom plug-in to examine V8 internals and it would help to get as close to the barebones as I can

**Comment by NathanaelA** [comment]
You have to read the V8 source code.  ;-)

**Comment by NathanaelA** [comment]
Yes, those two functions no longer exist.
The primary file for internal functions are:
  https://github.com/v8/v8/blob/master/src/runtime/runtime.h
