### ISSUE TITLE
testOptimization: 2 calls are needed to go from uninitialized -> pre-monomorphic -> monomorphic

### ISSUE THREAD

**Issue by guymguym** [NathanaelA/v8-Natives#11]
Hi,

See this comment in:
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#1-tooling

So perhaps better run the functions twice in `testOptimization` before the check?

Thanks!

**Comment by NathanaelA** [comment]
Thanks for the heads up.   I have updated the source code and published a new version.
