### ISSUE TITLE
Unable to run browser example with Chrome 62.0.3202 on MacOS 10.13

### ISSUE THREAD

**Issue by tolgap** [NathanaelA/v8-Natives#12]
Here are my steps:

```
git clone
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
cd examples
chrome --js-flags="--allow-natives-syntax" browser.html
```

Is there anything else I should know about? I've tried many variations of flags. The node variant works for me, but not the browser variant. It does enable `%GetOptimizationStatus()`. `%FunctionGetName()`, but not `%GetV8Version()` and `%GetOptimizationCount()`.

**Comment by lauriro** [comment]
GetV8Version [is removed from v8](https://github.com/v8/v8/commit/7ddc8245aff08f9a97e1c72d185d349e8b8d6105)

**Comment by NathanaelA** [comment]
@lauriro - Thanks for the heads up.  I'll remove those from the codebase here.

**Comment by NathanaelA** [comment]
I've updated the code base and those (and a couple others) have been removed/replaced.
