### ISSUE TITLE
getOptimizationStatus

### ISSUE THREAD

**Issue by julianjensen** [NathanaelA/v8-Natives#5]
From looking at the source code for _getOptimizationStatus_, it looks like the values below can be returned. It also looks like it takes 1 or 2 arguments, the first being the function, of course, the second being a boolean that tells V8 to sync with the compilation thread or not. The default is _true_ but can be set to _false_, making this call a bit faster (but probably less reliable in terms of the validity of its reply).

Return values:
* 1 - Yes
* 2 - No
* 3 - Always
* 4 - Never
* 5 - ??? Don't see it returned at all
* 6 - Maybe de-optimized
* 7 - TurboFan compiler

Here's the function source code from _v8/src/runtime/runtime-test.cc_:

```cpp
RUNTIME_FUNCTION(Runtime_GetOptimizationStatus) {
  HandleScope scope(isolate);
  RUNTIME_ASSERT(args.length() == 1 || args.length() == 2);
  if (!isolate->use_crankshaft()) {
    return Smi::FromInt(4);  // 4 == "never".
  }
  bool sync_with_compiler_thread = true;
  if (args.length() == 2) {
    CONVERT_ARG_HANDLE_CHECKED(String, sync, 1);
    if (sync->IsOneByteEqualTo(STATIC_CHAR_VECTOR("no sync"))) {
      sync_with_compiler_thread = false;
    }
  }
  CONVERT_ARG_HANDLE_CHECKED(JSFunction, function, 0);
  if (isolate->concurrent_recompilation_enabled() &&
      sync_with_compiler_thread) {
    while (function->IsInOptimizationQueue()) {
      isolate->optimizing_compile_dispatcher()->InstallOptimizedFunctions();
      base::OS::Sleep(base::TimeDelta::FromMilliseconds(50));
    }
  }
  if (FLAG_always_opt || FLAG_prepare_always_opt) {
    // With --always-opt, optimization status expectations might not
    // match up, so just return a sentinel.
    return Smi::FromInt(3);  // 3 == "always".
  }
  if (FLAG_deopt_every_n_times) {
    return Smi::FromInt(6);  // 6 == "maybe deopted".
  }
  if (function->IsOptimized() && function->code()->is_turbofanned()) {
    return Smi::FromInt(7);  // 7 == "TurboFan compiler".
  }
  return function->IsOptimized() ? Smi::FromInt(1)   // 1 == "yes".
                                 : Smi::FromInt(2);  // 2 == "no".
}
```
_Smi_, by the way, is small integer. An _isolate_ is a sanboxed instance of V8.

Anyway, this isn't really an "issue", just wanted to clarify your documentation. Also, there's lots to learn from looking through the _v8/src/runtime/_ directory but bear in mind that the V8 source code is gnarly, badly formatted, everything's poorly named, and there are practically no comments. :) That being said, some pretty smart code in there.

Julian

**Comment by NathanaelA** [comment]
Sweet, thanks for that.  I'll try and see if I can get the docs updated.   I need to spend some time and go back through that code and see if their are new functions that I haven't exposed since my release of this ages ago...   (And yeah, they have some really smart coders on that team!)

**Comment by NathanaelA** [comment]
Thanks, I have finally spent the time to update the code base and added TurboFan to the code base.  I would rather this function is slightly slower and be accurate.  I also have added a couple more additional v8 functions.
