### ISSUE TITLE
Programmatically taking heap snapshots

### ISSUE THREAD

**Issue by myitcv** [NathanaelA/v8-Natives#7]
Stumbled across repo, looks very interesting. 

Chrome's heap snapshots and heap profiling provide lots of useful information:

https://developers.google.com/web/tools/chrome-devtools/profile/memory-problems/heap-snapshots

We want to be able to:

* programmatically take snapshots and profiles and
* make assertions about object count, shallow size and retained size for these snapshots/profiles

Can you help to point us in the right direction?

Thanks

**Comment by NathanaelA** [comment]
Actually this repo is probably what you want (or at a minimum a place you can start with to understand the v8 native commands).  By using the v8 native commands you can actually work with the low levels of the v8 engine which I'm pretty sure includes programmatically taking snapshots.   

Now as to parsing the snapshot; you probably need to dive into the v8 engine to understand the heap snapshot formats and how they are built if you want a custom tool for it.  However you might also be able to find a low level v8 command to read, parse, and spit out that data; but without spending time digging into the v8 engine I wouldn't know for sure.  The final options is you could hire someone with experience in v8 (I should mention I am a freelance contractor) to add code to your own copy of the v8 engine that can read in the heap snapshots like normal  and then spits out all the data in a easy to use json or some other data format for your tools to parse and use.

**Comment by myitcv** [comment]
@NathanaelA thanks for the detailed response.

For now I have found https://github.com/bnoordhuis/node-heapdump which does what we need as far as programmatically taking heap snapshots is concerned.

Also the snapshot format looks relatively simple to parse for our requirements.

Thanks again

**Comment by NathanaelA** [comment]
Awesome, I am glad that you found a tool that would work for you!   Thanks for the pointer to it; I hadn't seen that tool yet -- not a huge number of debugging tools yet in the eco-system; so I will have to check it out.  :+1:
