### ISSUE TITLE
broken in Node 6.0

### ISSUE THREAD

**Issue by hax** [NathanaelA/v8-Natives#8]
Error info:
```
        return %IsInPrototypeChain(value, proto);
                                               ^
SyntaxError: IsInPrototypeChain is not defined
```

**Comment by NathanaelA** [comment]
They actually renamed it in v8 5.0 to %HasInPrototypeChain

We need to add some code to detect the engine version and then use the proper name...

**Comment by NathanaelA** [comment]
I messed around with isInPrototypeChain and HasInPrototypeChain and they don't appear to work the way I would expect them too; so I have just removed them in the next version just to simplify the code base.  I just published and added a couple new functions.
